name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
permissions:
  contents: read
jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: keycloak
          POSTGRES_DB: keycloak
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        os: [ 1, 2, 3, 4, 5 ]
        # Keep this list as: all supported LTS JDKs, the latest GA JDK, and the latest EA JDK (optional).
        java: [ 11, 17, 21, 23 ]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build with Maven
        # In order to support Windows PowerShell, a space between --define property=true is required.
        run: mvn --batch-mode --no-transfer-progress verify -Dtest=JDBC_PING2_Test
